# Generated by Django 4.2.6 on 2023-10-19 18:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('mobile_operator_code', models.CharField(max_length=3)),
                ('tag', models.CharField(max_length=255)),
                ('timezone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('text', models.CharField()),
                ('mobile_operator_filter', models.CharField(max_length=3, null=True)),
                ('tag_filter', models.CharField(max_length=255, null=True)),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField()),
                ('status', models.CharField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mailing')),
            ],
        ),
    ]
